import { supabase } from '@/integrations/supabase/client';

export interface PatientPayload {
  full_name: string;
    phone: string;
      gender: 'male' | 'female';
        date_of_birth?: string;
          age?: number;
            address?: string;
            }

            export interface VisitPayload {
              patient_id: string;
                branch_id?: string;
                  department_id?: string;
                    doctor_id?: string;
                      visit_type?: string;
                        chief_complaint?: string;
                        }

                        export interface QueuePayload {
                          patient_id: string;
                            visit_id: string;
                              department_id?: string;
                                doctor_id?: string;
                                }

                                export interface InvoiceItemPayload {
                                  description: string;
                                    quantity: number;
                                      unit_price: number;
                                        total_price: number;
                                        }

                                        export interface InvoicePayload {
                                          patient_id: string;
                                            visit_id: string;
                                              total_amount: number;
                                                discount_amount?: number;
                                                  net_amount: number;
                                                    items: InvoiceItemPayload[];
                                                    }

                                                    export interface PaymentPayload {
                                                      invoice_id: string;
                                                        amount: number;
                                                          payment_method: 'cash' | 'bankak' | 'other';
                                                            reference_number?: string;
                                                            }

                                                            export const receptionService = {
                                                              // 1. Create Patient
                                                                async createPatient(payload: PatientPayload) {
                                                                    const { data, error } = await supabase
                                                                          .from('patients')
                                                                                .insert([payload])
                                                                                      .select()
                                                                                            .single();
                                                                                                if (error) throw new Error(`خطأ أثناء إضافة المريض: ${error.message}`);
                                                                                                    return data;
                                                                                                      },

                                                                                                        // 2. Start Visit
                                                                                                          async createVisit(payload: VisitPayload) {
                                                                                                              const { data, error } = await supabase
                                                                                                                    .from('visits')
                                                                                                                          .insert([{
                                                                                                                                  patient_id: payload.patient_id,
                                                                                                                                          branch_id: payload.branch_id,
                                                                                                                                                  department_id: payload.department_id,
                                                                                                                                                          doctor_id: payload.doctor_id,
                                                                                                                                                                  visit_type: payload.visit_type || 'consultation',
                                                                                                                                                                          status: 'active',
                                                                                                                                                                                  chief_complaint: payload.chief_complaint
                                                                                                                                                                                        }])
                                                                                                                                                                                              .select()
                                                                                                                                                                                                    .single();
                                                                                                                                                                                                        if (error) throw new Error(`خطأ أثناء فتح الزيارة: ${error.message}`);
                                                                                                                                                                                                            return data;
                                                                                                                                                                                                              },

                                                                                                                                                                                                                // 3. Issue Queue Ticket
                                                                                                                                                                                                                  async createQueueTicket(payload: QueuePayload) {
                                                                                                                                                                                                                      // Generate simple sequential ticket number if not auto-generated
                                                                                                                                                                                                                          const ticketNumber = Math.floor(100 + Math.random() * 900).toString();

                                                                                                                                                                                                                              const { data, error } = await supabase
                                                                                                                                                                                                                                    .from('queue_tickets')
                                                                                                                                                                                                                                          .insert([{
                                                                                                                                                                                                                                                  patient_id: payload.patient_id,
                                                                                                                                                                                                                                                          visit_id: payload.visit_id,
                                                                                                                                                                                                                                                                  department_id: payload.department_id,
                                                                                                                                                                                                                                                                          doctor_id: payload.doctor_id,
                                                                                                                                                                                                                                                                                  ticket_number: ticketNumber,
                                                                                                                                                                                                                                                                                          status: 'waiting'
                                                                                                                                                                                                                                                                                                }])
                                                                                                                                                                                                                                                                                                      .select()
                                                                                                                                                                                                                                                                                                            .single();
                                                                                                                                                                                                                                                                                                                if (error) throw new Error(`خطأ أثناء إيقاف التذكرة في الانتظار: ${error.message}`);
                                                                                                                                                                                                                                                                                                                    return data;
                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                        // 4. Create Invoice and Line Items
                                                                                                                                                                                                                                                                                                                          async createInvoice(payload: InvoicePayload) {
                                                                                                                                                                                                                                                                                                                              const { data: invoice, error: invoiceError } = await supabase
                                                                                                                                                                                                                                                                                                                                    .from('invoices')
                                                                                                                                                                                                                                                                                                                                          .insert([{
                                                                                                                                                                                                                                                                                                                                                  patient_id: payload.patient_id,
                                                                                                                                                                                                                                                                                                                                                          visit_id: payload.visit_id,
                                                                                                                                                                                                                                                                                                                                                                  total_amount: payload.total_amount,
                                                                                                                                                                                                                                                                                                                                                                          discount_amount: payload.discount_amount || 0,
                                                                                                                                                                                                                                                                                                                                                                                  net_amount: payload.net_amount,
                                                                                                                                                                                                                                                                                                                                                                                          status: 'pending'
                                                                                                                                                                                                                                                                                                                                                                                                }])
                                                                                                                                                                                                                                                                                                                                                                                                      .select()
                                                                                                                                                                                                                                                                                                                                                                                                            .single();

                                                                                                                                                                                                                                                                                                                                                                                                                if (invoiceError) throw new Error(`خطأ أثناء إنشاء الفاتورة: ${invoiceError.message}`);

                                                                                                                                                                                                                                                                                                                                                                                                                    if (payload.items && payload.items.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                          const itemsToInsert = payload.items.map((item) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                  invoice_id: invoice.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                          description: item.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  quantity: item.quantity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          unit_price: item.unit_price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  total_price: item.total_price
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const { error: itemsError } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .from('invoice_items')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .insert(itemsToInsert);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (itemsError) throw new Error(`خطأ أثناء إدخال بنود الفاتورة: ${itemsError.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return invoice;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 5. Process Payment (Cash / Bankak)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async processPayment(payload: PaymentPayload) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const { data: payment, error: paymentError } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('payments')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .insert([{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          invoice_id: payload.invoice_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  amount: payload.amount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          payment_method: payload.payment_method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  reference_number: payload.reference_number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .select()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (paymentError) throw new Error(`خطأ أثناء تسجيل الدفع: ${paymentError.message}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Update invoice status to paid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { error: updateInvoiceError } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .from('invoices')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .update({ status: 'paid' })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .eq('id', payload.invoice_id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (updateInvoiceError) throw new Error(`خطأ أثناء تحديث حالة الفاتورة: ${updateInvoiceError.message}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return payment;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Consolidated Pipeline Execution
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async executeFullReceptionWorkflow(data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    patient: PatientPayload;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        visit: Omit<VisitPayload, 'patient_id'>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            invoiceItems: InvoiceItemPayload[];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                paymentMethod: 'cash' | 'bankak';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    paymentReference?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Step 1: Patient
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const patientRecord = await this.createPatient(data.patient);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Step 2: Visit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const visitRecord = await this.createVisit({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...data.visit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  patient_id: patientRecord.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Step 3: Queue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const queueRecord = await this.createQueueTicket({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    patient_id: patientRecord.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          visit_id: visitRecord.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                department_id: data.visit.department_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      doctor_id: data.visit.doctor_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Step 4: Invoice
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const totalAmount = data.invoiceItems.reduce((acc, curr) => acc + curr.total_price, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const invoiceRecord = await this.createInvoice({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            patient_id: patientRecord.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  visit_id: visitRecord.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        total_amount: totalAmount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              net_amount: totalAmount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    items: data.invoiceItems
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Step 5: Payment
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const paymentRecord = await this.processPayment({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      invoice_id: invoiceRecord.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            amount: totalAmount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  payment_method: data.paymentMethod,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reference_number: data.paymentReference
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      patient: patientRecord,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            visit: visitRecord,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  queue: queueRecord,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        invoice: invoiceRecord,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              payment: paymentRecord
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    