/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedClinicRouteImport } from './routes/_authenticated/clinic'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedLabCatalogRouteImport } from './routes/_authenticated/lab-catalog'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedVisitsRouteImport } from './routes/_authenticated/visits'
import { Route as AuthenticatedBillingInvoiceIdRouteImport } from './routes/_authenticated/billing.$invoiceId'
import { Route as AuthenticatedClinicVisitIdRouteImport } from './routes/_authenticated/clinic.$visitId'
import { Route as AuthenticatedLabOrderIdRouteImport } from './routes/_authenticated/lab.$orderId'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClinicRoute = AuthenticatedClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabCatalogRoute = AuthenticatedLabCatalogRouteImport.update({
  id: '/lab-catalog',
  path: '/lab-catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsRoute = AuthenticatedVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingInvoiceIdRoute =
  AuthenticatedBillingInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedBillingRoute,
  } as any)
const AuthenticatedClinicVisitIdRoute =
  AuthenticatedClinicVisitIdRouteImport.update({
    id: '/$visitId',
    path: '/$visitId',
    getParentRoute: () => AuthenticatedClinicRoute,
  } as any)
const AuthenticatedLabOrderIdRoute = AuthenticatedLabOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AuthenticatedLabRoute,
} as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/clinic': typeof AuthenticatedClinicRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/lab': typeof AuthenticatedLabRouteWithChildren
  '/lab-catalog': typeof AuthenticatedLabCatalogRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/billing/$invoiceId': typeof AuthenticatedBillingInvoiceIdRoute
  '/clinic/$visitId': typeof AuthenticatedClinicVisitIdRoute
  '/lab/$orderId': typeof AuthenticatedLabOrderIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/clinic': typeof AuthenticatedClinicRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/lab': typeof AuthenticatedLabRouteWithChildren
  '/lab-catalog': typeof AuthenticatedLabCatalogRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/billing/$invoiceId': typeof AuthenticatedBillingInvoiceIdRoute
  '/clinic/$visitId': typeof AuthenticatedClinicVisitIdRoute
  '/lab/$orderId': typeof AuthenticatedLabOrderIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRouteWithChildren
  '/_authenticated/clinic': typeof AuthenticatedClinicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/lab': typeof AuthenticatedLabRouteWithChildren
  '/_authenticated/lab-catalog': typeof AuthenticatedLabCatalogRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/visits': typeof AuthenticatedVisitsRoute
  '/_authenticated/billing/$invoiceId': typeof AuthenticatedBillingInvoiceIdRoute
  '/_authenticated/clinic/$visitId': typeof AuthenticatedClinicVisitIdRoute
  '/_authenticated/lab/$orderId': typeof AuthenticatedLabOrderIdRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/appointments'
    | '/billing'
    | '/clinic'
    | '/dashboard'
    | '/inventory'
    | '/lab'
    | '/lab-catalog'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/visits'
    | '/billing/$invoiceId'
    | '/clinic/$visitId'
    | '/lab/$orderId'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/appointments'
    | '/billing'
    | '/clinic'
    | '/dashboard'
    | '/inventory'
    | '/lab'
    | '/lab-catalog'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/visits'
    | '/billing/$invoiceId'
    | '/clinic/$visitId'
    | '/lab/$orderId'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/appointments'
    | '/_authenticated/billing'
    | '/_authenticated/clinic'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/lab'
    | '/_authenticated/lab-catalog'
    | '/_authenticated/patients'
    | '/_authenticated/pharmacy'
    | '/_authenticated/queue'
    | '/_authenticated/visits'
    | '/_authenticated/billing/$invoiceId'
    | '/_authenticated/clinic/$visitId'
    | '/_authenticated/lab/$orderId'
    | '/_authenticated/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinic': {
      id: '/_authenticated/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof AuthenticatedClinicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab-catalog': {
      id: '/_authenticated/lab-catalog'
      path: '/lab-catalog'
      fullPath: '/lab-catalog'
      preLoaderRoute: typeof AuthenticatedLabCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits': {
      id: '/_authenticated/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/$invoiceId': {
      id: '/_authenticated/billing/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/billing/$invoiceId'
      preLoaderRoute: typeof AuthenticatedBillingInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/clinic/$visitId': {
      id: '/_authenticated/clinic/$visitId'
      path: '/$visitId'
      fullPath: '/clinic/$visitId'
      preLoaderRoute: typeof AuthenticatedClinicVisitIdRouteImport
      parentRoute: typeof AuthenticatedClinicRoute
    }
    '/_authenticated/lab/$orderId': {
      id: '/_authenticated/lab/$orderId'
      path: '/$orderId'
      fullPath: '/lab/$orderId'
      preLoaderRoute: typeof AuthenticatedLabOrderIdRouteImport
      parentRoute: typeof AuthenticatedLabRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
  }
}

interface AuthenticatedBillingRouteChildren {
  AuthenticatedBillingInvoiceIdRoute: typeof AuthenticatedBillingInvoiceIdRoute
}

const AuthenticatedBillingRouteChildren: AuthenticatedBillingRouteChildren = {
  AuthenticatedBillingInvoiceIdRoute: AuthenticatedBillingInvoiceIdRoute,
}

const AuthenticatedBillingRouteWithChildren =
  AuthenticatedBillingRoute._addFileChildren(AuthenticatedBillingRouteChildren)

interface AuthenticatedClinicRouteChildren {
  AuthenticatedClinicVisitIdRoute: typeof AuthenticatedClinicVisitIdRoute
}

const AuthenticatedClinicRouteChildren: AuthenticatedClinicRouteChildren = {
  AuthenticatedClinicVisitIdRoute: AuthenticatedClinicVisitIdRoute,
}

const AuthenticatedClinicRouteWithChildren =
  AuthenticatedClinicRoute._addFileChildren(AuthenticatedClinicRouteChildren)

interface AuthenticatedLabRouteChildren {
  AuthenticatedLabOrderIdRoute: typeof AuthenticatedLabOrderIdRoute
}

const AuthenticatedLabRouteChildren: AuthenticatedLabRouteChildren = {
  AuthenticatedLabOrderIdRoute: AuthenticatedLabOrderIdRoute,
}

const AuthenticatedLabRouteWithChildren =
  AuthenticatedLabRoute._addFileChildren(AuthenticatedLabRouteChildren)

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRouteWithChildren
  AuthenticatedClinicRoute: typeof AuthenticatedClinicRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRouteWithChildren
  AuthenticatedLabCatalogRoute: typeof AuthenticatedLabCatalogRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedVisitsRoute: typeof AuthenticatedVisitsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRouteWithChildren,
  AuthenticatedClinicRoute: AuthenticatedClinicRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLabRoute: AuthenticatedLabRouteWithChildren,
  AuthenticatedLabCatalogRoute: AuthenticatedLabCatalogRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedVisitsRoute: AuthenticatedVisitsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
