/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedClinicRouteImport } from './routes/_authenticated/clinic'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedLabCatalogRouteImport } from './routes/_authenticated/lab-catalog'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVisitsRouteImport } from './routes/_authenticated/visits'
import { Route as AuthenticatedBillingInvoiceIdRouteImport } from './routes/_authenticated/billing.$invoiceId'
import { Route as AuthenticatedClinicVisitIdRouteImport } from './routes/_authenticated/clinic_.$visitId'
import { Route as AuthenticatedLabOrderIdRouteImport } from './routes/_authenticated/lab.$orderId'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients_.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClinicRoute = AuthenticatedClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabCatalogRoute = AuthenticatedLabCatalogRouteImport.update({
  id: '/lab-catalog',
  path: '/lab-catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsRoute = AuthenticatedVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingInvoiceIdRoute =
  AuthenticatedBillingInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedBillingRoute,
  } as any)
const AuthenticatedClinicVisitIdRoute =
  AuthenticatedClinicVisitIdRouteImport.update({
    id: '/clinic_/$visitId',
    path: '/clinic/$visitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabOrderIdRoute = AuthenticatedLabOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AuthenticatedLabRoute,
} as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients_/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/clinic': typeof AuthenticatedClinicRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/lab': typeof AuthenticatedLabRouteWithChildren
  '/lab-catalog': typeof AuthenticatedLabCatalogRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/billing/$invoiceId': typeof AuthenticatedBillingInvoiceIdRoute
  '/clinic/$visitId': typeof AuthenticatedClinicVisitIdRoute
  '/lab/$orderId': typeof AuthenticatedLabOrderIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/clinic': typeof AuthenticatedClinicRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/lab': typeof AuthenticatedLabRouteWithChildren
  '/lab-catalog': typeof AuthenticatedLabCatalogRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/billing/$invoiceId': typeof AuthenticatedBillingInvoiceIdRoute
  '/clinic/$visitId': typeof AuthenticatedClinicVisitIdRoute
  '/lab/$orderId': typeof AuthenticatedLabOrderIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRouteWithChildren
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/clinic': typeof AuthenticatedClinicRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/lab': typeof AuthenticatedLabRouteWithChildren
  '/_authenticated/lab-catalog': typeof AuthenticatedLabCatalogRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/visits': typeof AuthenticatedVisitsRoute
  '/_authenticated/billing/$invoiceId': typeof AuthenticatedBillingInvoiceIdRoute
  '/_authenticated/clinic_/$visitId': typeof AuthenticatedClinicVisitIdRoute
  '/_authenticated/lab/$orderId': typeof AuthenticatedLabOrderIdRoute
  '/_authenticated/patients_/$patientId': typeof AuthenticatedPatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/accounting'
    | '/appointments'
    | '/audit'
    | '/billing'
    | '/certificates'
    | '/clinic'
    | '/dashboard'
    | '/expenses'
    | '/followups'
    | '/inventory'
    | '/lab'
    | '/lab-catalog'
    | '/partners'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/users'
    | '/visits'
    | '/billing/$invoiceId'
    | '/clinic/$visitId'
    | '/lab/$orderId'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/accounting'
    | '/appointments'
    | '/audit'
    | '/billing'
    | '/certificates'
    | '/clinic'
    | '/dashboard'
    | '/expenses'
    | '/followups'
    | '/inventory'
    | '/lab'
    | '/lab-catalog'
    | '/partners'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/users'
    | '/visits'
    | '/billing/$invoiceId'
    | '/clinic/$visitId'
    | '/lab/$orderId'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/accounting'
    | '/_authenticated/appointments'
    | '/_authenticated/audit'
    | '/_authenticated/billing'
    | '/_authenticated/certificates'
    | '/_authenticated/clinic'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/followups'
    | '/_authenticated/inventory'
    | '/_authenticated/lab'
    | '/_authenticated/lab-catalog'
    | '/_authenticated/partners'
    | '/_authenticated/patients'
    | '/_authenticated/pharmacy'
    | '/_authenticated/queue'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/visits'
    | '/_authenticated/billing/$invoiceId'
    | '/_authenticated/clinic_/$visitId'
    | '/_authenticated/lab/$orderId'
    | '/_authenticated/patients_/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinic': {
      id: '/_authenticated/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof AuthenticatedClinicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab-catalog': {
      id: '/_authenticated/lab-catalog'
      path: '/lab-catalog'
      fullPath: '/lab-catalog'
      preLoaderRoute: typeof AuthenticatedLabCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits': {
      id: '/_authenticated/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/$invoiceId': {
      id: '/_authenticated/billing/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/billing/$invoiceId'
      preLoaderRoute: typeof AuthenticatedBillingInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/clinic_/$visitId': {
      id: '/_authenticated/clinic_/$visitId'
      path: '/clinic/$visitId'
      fullPath: '/clinic/$visitId'
      preLoaderRoute: typeof AuthenticatedClinicVisitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab/$orderId': {
      id: '/_authenticated/lab/$orderId'
      path: '/$orderId'
      fullPath: '/lab/$orderId'
      preLoaderRoute: typeof AuthenticatedLabOrderIdRouteImport
      parentRoute: typeof AuthenticatedLabRoute
    }
    '/_authenticated/patients_/$patientId': {
      id: '/_authenticated/patients_/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedBillingRouteChildren {
  AuthenticatedBillingInvoiceIdRoute: typeof AuthenticatedBillingInvoiceIdRoute
}

const AuthenticatedBillingRouteChildren: AuthenticatedBillingRouteChildren = {
  AuthenticatedBillingInvoiceIdRoute: AuthenticatedBillingInvoiceIdRoute,
}

const AuthenticatedBillingRouteWithChildren =
  AuthenticatedBillingRoute._addFileChildren(AuthenticatedBillingRouteChildren)

interface AuthenticatedLabRouteChildren {
  AuthenticatedLabOrderIdRoute: typeof AuthenticatedLabOrderIdRoute
}

const AuthenticatedLabRouteChildren: AuthenticatedLabRouteChildren = {
  AuthenticatedLabOrderIdRoute: AuthenticatedLabOrderIdRoute,
}

const AuthenticatedLabRouteWithChildren =
  AuthenticatedLabRoute._addFileChildren(AuthenticatedLabRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRouteWithChildren
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedClinicRoute: typeof AuthenticatedClinicRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRouteWithChildren
  AuthenticatedLabCatalogRoute: typeof AuthenticatedLabCatalogRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVisitsRoute: typeof AuthenticatedVisitsRoute
  AuthenticatedClinicVisitIdRoute: typeof AuthenticatedClinicVisitIdRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRouteWithChildren,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedClinicRoute: AuthenticatedClinicRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLabRoute: AuthenticatedLabRouteWithChildren,
  AuthenticatedLabCatalogRoute: AuthenticatedLabCatalogRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVisitsRoute: AuthenticatedVisitsRoute,
  AuthenticatedClinicVisitIdRoute: AuthenticatedClinicVisitIdRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
